INSERT INTO tb_category(name, created_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computadores', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Roupas', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eletrodomésticos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Móveis', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Brinquedos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos Esportivos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Instrumentos Musicais', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Filmes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jogos de Vídeo', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Ferramentas', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotivos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Saúde e Beleza', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Alimentos e Bebidas', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Joias', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Produtos para Animais de Estimação', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Materiais de Artesanato', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Produtos para Bebês', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Material de Escritório', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jardinagem', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Acessórios de Viagem', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos para Exteriores', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Utensílios de Cozinha', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Material de Papelaria', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Artigos para Festa', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Acessórios Musicais', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kits de Artesanato', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Materiais para DIY', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Relógios', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Óculos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Bolsas e Malas', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Decoração de Casa', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Decorações de Festa', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Camping', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Brinquedos Educativos', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Roupas de Fitness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Caminhada', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Acessórios para Celular', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Materiais para Pintura', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Pesca', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Materiais para Escultura', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Fotografia', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Acessórios de Moda', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jogos de Tabuleiro', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Bicicletas', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Escalada', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Roupas de Banho', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Equipamentos de Surf', NOW());
